version: '3'

services:
  automation-rpa:
    image: felipealfah/pwads_automation:1.0
    # Adicionar opção de build local como fallback
    build:
      context: ./automation_py
      dockerfile: dockerfile
    container_name: automation-rpa
    restart: unless-stopped
    ports:
      - "5001:5001"  # Porta para webhook
      - "8501:8501"  # Porta para Streamlit
    volumes:
      - ./automation_py:/app
      - shared_data:/shared
    environment:
      - PYTHONUNBUFFERED=1
      # Variáveis de ambiente para conectividade com o AdsPower
      - ADSPOWER_HOST=${ADSPOWER_HOST:-host.docker.internal}
      - ADSPOWER_PORT=${ADSPOWER_PORT:-50325}
    extra_hosts:
      # Configuração para acessar o host a partir do container (funciona em todas as plataformas)
      - "host.docker.internal:host-gateway"
    networks:
      - automation-network
    # Configuração para ajudar no debugging
    tty: true
    stdin_open: true

networks:
  automation-network:
    driver: bridge

volumes:
  shared_data:
    # Driver local para compatibilidade em diferentes sistemas
    driver: local